/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redex_JNIExample */

#ifndef _Included_redex_JNIExample
#define _Included_redex_JNIExample
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_redex_JNIExample_unused(JNIEnv*, jobject);

JNIEXPORT void JNICALL Java_redex_JNIExample_implemented(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
