name: test-build-setup
inputs:
  use_sdk:
    required: false
    default: true
runs:
  using: composite
  steps:
  - uses: "./.github/actions/test-build-setup-sdk"
    if: inputs.use_sdk == 'true'
  - uses: "./.github/actions/test-build-setup-no-sdk"
    if: inputs.use_sdk != 'true'
