name: test-build-setup
runs:
  using: composite
  steps:
  - name: Setup for tests
    run: sudo apt-get install -y --no-install-recommends default-jdk-headless
    shell: bash
  - name: Set cache version
    id: cache_version
    run: |-
      echo "Cache key is: ${CACHE_VERSION}"
      echo "CACHE_VERSION=${CACHE_VERSION}" >> "$GITHUB_OUTPUT"
    shell: bash
  - name: Cache SDK
    uses: actions/cache@v3.3.2
    with:
      key: v1-android-build-tools
      path: sdk.tar.zstd
      restore-keys: v1-android-build-tools
  - name: Check/Install (SDK)
    run: |-
      if [ -e sdk/build-tools/29.0.2/dx ] ; then echo "Found SDK." ; exit 0 ; fi

      # Check whether cache file exists, then check dx again.
      if [ -f "sdk.tar.zstd" ] ; then
        zstd --decompress --stdout sdk.tar.zstd | tar xf -
        if [ -e sdk/build-tools/29.0.2/dx ] ; then echo "Unpacked SDK." ; exit 0 ; fi
      fi

      # Download.
      echo "SDK missing, downloading..."
      rm -rf sdk 2>/dev/null && mkdir -p sdk/cmdline-tools
      echo "Downloading SDK to $(pwd)/sdk"
      wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
      unzip commandlinetools-linux-6609375_latest.zip -d sdk/cmdline-tools/
      pushd sdk/cmdline-tools/tools/bin >/dev/null
      echo 'y' | ./sdkmanager --install 'build-tools;29.0.2'
      popd >/dev/null

      # Compress for cache. For reason see description of build cache.
      # We do not need the emulator and it is large. Delete.
      rm -rf sdk/emulator 2>/dev/null
      tar cf - sdk | zstd -T0 -3 > sdk.tar.zstd
    shell: bash
