/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include "RClass.h"

#include <string>

namespace {
// Crude check for if the name matches the pattern of autogenerated R class.
bool is_resource_class_name(const std::string_view c_name) {
  return c_name.find("/R$") != std::string::npos;
}
} // namespace

namespace resources {
bool is_r_class(const DexClass* cls) {
  const auto c_name = cls->get_name()->str();
  const auto d_name = cls->get_deobfuscated_name_or_empty();
  return is_resource_class_name(c_name) || is_resource_class_name(d_name);
}
} // namespace resources
