name: setup-build-and-test-w-make
inputs:
  save_boost_cache:
    required: false
    default: false
  mode_32:
    required: false
    default: false
  use_sdk:
    required: false
    default: true
  job_name:
    required: false
runs:
  using: composite
  steps:
  - uses: "./.github/actions/setup-build-and-test-w-make-impl"
    if: inputs.mode_32 == 'true'
    with:
      setup_toolchain_extra: '32'
      configure_extra: "--host=i686-linux-gnu CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32"
      save_boost_cache: "${{ inputs.save_boost_cache }}"
      run_tests: false
      use_sdk: "${{ inputs.use_sdk }}"
      job_name: "${{ inputs.job_name }}"
  - uses: "./.github/actions/setup-build-and-test-w-make-impl"
    if: inputs.mode_32 != 'true'
    with:
      save_boost_cache: "${{ inputs.save_boost_cache }}"
      use_sdk: "${{ inputs.use_sdk }}"
      job_name: "${{ inputs.job_name }}"