name: build_debian
inputs:
  save_boost_cache:
    required: false
    default: false
  install_clang:
    required: false
    default: false
  install_clang_llvm_org:
    required: false
    default: -1
  mode_32:
    required: false
    default: false
  job_name:
    required: false
runs:
  using: composite
  steps:
  # Reinitialize. It is easier to do this (again) to not have to deal with
  # fixing `uses:` paths.
  - uses: actions/checkout@v4.1.1
    with:
      path: repo
      # We want to run restore-mtime, which needs to find actual commit data
      # and not just the shallow default result. The easiest way for this seems
      # to be the filter support of Github (https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/).
      fetch-depth: 1000000
      filter: "tree:0"
  - uses: ./.github/actions/debian-based-image-build-setup
    with:
      mode_32: "${{ inputs.mode_32 }}"
      install_clang: "${{ inputs.install_clang }}"
      install_clang_llvm_org: "${{ inputs.install_clang_llvm_org }}"
  - name: Run git-restore-mtime
    run: git restore-mtime
    working-directory: repo
    shell: bash
  - uses: ./.github/actions/setup-build-and-test-w-make
    with:
      save_boost_cache: "${{ inputs.save_boost_cache }}"
      mode_32: "${{ inputs.mode_32 }}"
      job_name: "${{ inputs.job_name }}-${{ inputs.install_clang_llvm_org }}"
