#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import argparse
import sqlite3
import sys

from lib.sqlite_export import export_graph


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Export a Redex reachability graph to SQLite."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Input file generated by Reachability.dump_graph()",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="Output SQLite database (must not already exist)",
    )
    return parser.parse_args(argv)


def main(argv):
    args = parse_args(argv)
    try:
        export_graph(args.input, args.output)
    except (OSError, ValueError, sqlite3.Error) as error:
        print("Error: %s" % error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
